name: Mirror Upstream Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour as an example
  workflow_dispatch:

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    name: Mirror the upstream repository

    steps:
      - name: Mirror the upstream repository to this repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Clone the repository using the --mirror flag with PAT for authentication
          git clone --mirror https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/pkarastelev/office-app.git temp

          # Navigate into the repository directory
          cd temp

          # Set the push URL to the destination repository, including the PAT for authentication
          git remote set-url --push origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/WSHAPER/office-app.git

          # Fetch all refs from origin
          git fetch origin

          # Optionally, list all refs you want to exclude
          # For example, to exclude pull request refs, you can list them explicitly or use patterns to exclude them
          # This step is manual and requires specifying what you want to exclude or include

          # Push everything except the excluded refs
          # Here, we're using a workaround by explicitly pushing branches and tags, excluding refs such as pull requests
          git push origin 'refs/tags/*:refs/tags/*'
          git push origin 'refs/heads/*:refs/heads/*'

          # Clean up
          cd ..
          rm -rf temp
