name: Mirror Upstream Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour as an example
  workflow_dispatch:

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    name: Mirror the upstream repository

    steps:
      - name: Mirror the upstream repository to this repository
        env:
          # Reference the PAT from your repository secrets
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Set up git to use the PAT for authentication
          git config --global credential.helper store

          # Save the PAT in the git-credentials file
          echo "https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com" > ~/.git-credentials

          # Clone the repository using the --mirror flag
          git clone --mirror https://github.com/pkarastelev/office-app.git temp

          # Go into the cloned directory
          cd temp

          # Push the mirror to the destination repository
          git push --mirror https://github.com/WSHAPER/office-app.git
