name: Mirror Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour as an example
  workflow_dispatch:

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    name: Mirror the upstream repository

    steps:
      - name: Mirror the upstream repository to this repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Clone the repository using the --mirror flag
          git clone --mirror https://github.com/pkarastelev/office-app.git temp

          # Navigate into the repository directory
          cd temp

          # Set the push URL to the destination repository, including the PAT for authentication
          git remote set-url --push origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/WSHAPER/office-app.git

          # Push the mirror to the destination repository
          git push --mirror

          # Clean up
          cd ..
          rm -rf temp
