name: Mirror Upstream Repository without PR refs

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour as an example
  workflow_dispatch:

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    name: Mirror the upstream repository

    steps:
      - name: Mirror the upstream repository to this repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Initialize an empty repository
          git init --bare temp
          cd temp

          # Add the source repo as a remote
          git remote add upstream https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/pkarastelev/office-app.git

          # Fetch all branches and tags from the upstream repository
          git fetch upstream '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*'

          # Set the push URL to the destination repository, including the PAT for authentication
          git remote set-url --push upstream https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/WSHAPER/office-app.git

          # Push the fetched branches and tags to the destination repository
          git push upstream --tags 'refs/heads/*:refs/heads/*'

          # Clean up
          cd ..
          rm -rf temp
