name: Mirror Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    name: Mirror the upstream repository

    steps:
      - name: Mirror the upstream repository to this repository
        run: |
          git clone --mirror https://github.com/pkarastelev/office-app.git temp
          cd temp
          git push --mirror https://github.com/WSHAPER/office-app.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
