name: Mirror Upstream Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour as an example
  workflow_dispatch:

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    name: Mirror the upstream repository

    steps:
      - name: Mirror the upstream repository to this repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Set up git to avoid prompting for user input
          git config --global --add safe.directory '*'
          
          # Clone the repository using the --mirror flag
          git clone --mirror https://github.com/pkarastelev/office-app.git temp

          # Navigate into the repository directory
          cd temp

          # Configure git to use the PAT for authentication
          git remote set-url origin https://${PERSONAL_ACCESS_TOKEN}@github.com/WSHAPER/office-app.git

          # Push the mirror to the destination repository, excluding pull request refs
          git for-each-ref --format='%(refname)' refs/heads/ refs/tags/ | xargs -L1 git push --mirror

          # Clean up
          cd ..
          rm -rf temp
