name: Mirror Upstream Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '45/60 * * * *'  # Runs every hour at 45 minutes past the hour

jobs:
  mirror_repos:
    runs-on: ubuntu-latest
    name: Mirror upstream repositories
    steps:
      - name: Mirror office-app upstream repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          mkdir temp1 && cd temp1
          git init
          git remote add upstream https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/kestr31/docker-stable-diffusion-webui.git
          git fetch upstream '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
          git remote add origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/WSHAPER/docker-stable-diffusion-webui.git
          git push origin --all
          git push origin --tags
          cd .. && rm -rf temp1

      - name: Mirror NoiseBuster upstream repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          mkdir temp2 && cd temp2
          git init
          git remote add upstream https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/silkyclouds/NoiseBuster.git
          git fetch upstream '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
          git remote add origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/WSHAPER/NoiseBuster.git
          git push origin --all
          git push origin --tags
          cd .. && rm -rf temp2
